id: com.antigravity_agent.app
runtime: org.gnome.Platform
runtime-version: '47'
sdk: org.gnome.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.rust-stable
  - org.freedesktop.Sdk.Extension.node22
command: antigravity-agent
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --share=network
  - --device=dri
modules:
  - name: libayatana-indicator
    buildsystem: cmake-ninja
    config-opts:
      - -DENABLE_TESTS=OFF
      - -DENABLE_LOMIRI_FEATURES=OFF
    sources:
      - type: git
        url: https://github.com/AyatanaIndicators/libayatana-indicator.git
        tag: 0.9.4

  - name: libayatana-appindicator
    buildsystem: cmake-ninja
    config-opts:
      - -DENABLE_TESTS=OFF
      - -DENABLE_BINDINGS_MONO=OFF
      - -DENABLE_LOMIRI_FEATURES=OFF
    sources:
      - type: git
        url: https://github.com/AyatanaIndicators/libayatana-appindicator.git
        tag: 0.5.93

  - name: libxdo
    buildsystem: simple
    build-commands:
      - make install PREFIX=/app
    sources:
      - type: git
        url: https://github.com/jordansissel/xdotool.git
        tag: v3.20211022.1

  - name: antigravity-agent
    buildsystem: simple
    build-options:
      build-args:
        - --share=network
      append-path: /usr/lib/sdk/node22/bin:/usr/lib/sdk/rust-stable/bin
      env:
        CARGO_HOME: /run/build/antigravity-agent/cargo
        npm_config_cache: /run/build/antigravity-agent/npm-cache
        tauri_build_profile: release
    build-commands:
      - npm install
      - npm run tauri build
      - install -Dm755 src-tauri/target/release/antigravity-agent /app/bin/antigravity-agent
      - install -Dm644 .github/flatpak/antigravity-agent.desktop /app/share/applications/com.antigravity_agent.app.desktop
      - install -Dm644 .github/flatpak/com.antigravity_agent.app.metainfo.xml /app/share/metainfo/com.antigravity_agent.app.metainfo.xml
      - install -Dm644 src-tauri/icons/128x128.png /app/share/icons/hicolor/128x128/apps/com.antigravity_agent.app.png
      - install -Dm644 src-tauri/icons/icon.png /app/share/icons/hicolor/512x512/apps/com.antigravity_agent.app.png
    sources:
      - type: dir
        path: ../../
